# Generated by Django 5.2.12 on 2026-04-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('costo_trabajo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'calculos',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'extras',
            },
        ),
        migrations.CreateModel(
            name='NotaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('contenido', models.TextField()),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notas_diarias',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'prendas',
            },
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'telas',
            },
        ),
        migrations.CreateModel(
            name='CalculoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='users.calculo')),
                ('extra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.extra')),
            ],
            options={
                'db_table': 'calculo_extras',
            },
        ),
        migrations.AddField(
            model_name='calculo',
            name='prenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.prenda'),
        ),
        migrations.CreateModel(
            name='CalculoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_usado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telas', to='users.calculo')),
                ('tela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tela')),
            ],
            options={
                'db_table': 'calculo_telas',
            },
        ),
        migrations.CreateModel(
            name='TelaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='users.tela')),
            ],
            options={
                'db_table': 'telas_precios',
                'unique_together': {('tela', 'fecha')},
            },
        ),
    ]
