# Generated by Django 5.2.12 on 2026-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('minimo_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.CharField(default='General', max_length=50)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
