# Generated by Django 5.2.12 on 2026-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='color',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.CharField(default='Disponible', max_length=20),
        ),
    ]
